name: yolo
description: "Vision AI Demos Project"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  camera: ^0.11.3
  tflite_flutter: ^0.12.1
  image: ^4.5.4
  flutter_screenutil: ^5.9.3
  go_router: ^17.0.0
  ffi_plugin_look:
    git:
      url: https://github.com/cornpip/ffi_plugin_test.git
      ref: master
#    path: ../ffi_plugin_test

  mediapipe_face_mesh: ^1.1.1
  google_mlkit_face_detection: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/models/YOLOv11-nano.tflite
    - assets/labels/coco_labels.txt